---
- name: Query API of Ice and Fire
  hosts: localhost
  gather_facts: no     # set to true by default, runs the "setup" module
  
    
  tasks:
  - name: Get data via API
    uri:
      url: https://anapioficeandfire.com/api/characters/583
    register: jsondata     # the "register" keyword is not part of the uri module
                             # just like the "become" keyword, this augments how a module executes
                              # in this case, we want to save the response returned by this module
                              # ALL modules in Ansible return data. Think of it as the "results" of how the
                              # task ran.
                              
  - name: Display the contents of the variable jsondata
    debug:
      var: item                                          
    loop: "{{ jsondata.json.aliases }}"
